#!/bin/bash
# Deployment script for Q&A Practice Application
# Usage: ./scripts/deploy.sh [environment]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default environment
ENVIRONMENT=${1:-development}

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Q&A Practice Application Deployment${NC}"
echo -e "${GREEN}Environment: ${ENVIRONMENT}${NC}"
echo -e "${GREEN}========================================${NC}"

# Function to print status
print_status() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    echo ""
    echo "Checking prerequisites..."
    
    # Check Python
    if command -v python3 &> /dev/null; then
        PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
        print_status "Python ${PYTHON_VERSION} found"
    else
        print_error "Python 3 is required but not installed"
        exit 1
    fi
    
    # Check uv
    if command -v uv &> /dev/null; then
        UV_VERSION=$(uv --version 2>&1 | head -1)
        print_status "uv ${UV_VERSION} found"
    else
        print_warning "uv not found, installing..."
        curl -LsSf https://astral.sh/uv/install.sh | sh
    fi
    
    # Check if question bank exists
    if [ -f "src/main/resources/question-bank.csv" ]; then
        print_status "Question bank CSV found"
    else
        print_error "Question bank CSV not found at src/main/resources/question-bank.csv"
        exit 1
    fi
}

# Setup environment
setup_environment() {
    echo ""
    echo "Setting up environment..."
    
    # Create .env file if it doesn't exist
    if [ ! -f ".env" ]; then
        cat > .env << EOF
# Q&A Practice Application Environment Configuration
# Generated by deploy.sh on $(date)

# Application Settings
QAA_DEBUG=${ENVIRONMENT:-development}
QAA_HOST=0.0.0.0
QAA_PORT=8000
QAA_LOG_LEVEL=INFO

# Session Settings
QAA_DEFAULT_SESSION_LENGTH=10
QAA_MIN_SESSION_LENGTH=5
QAA_MAX_SESSION_LENGTH=50

# File Paths
QAA_QUESTION_BANK_PATH=src/main/resources/question-bank.csv

# Performance Settings
QAA_CSV_PARSE_TIMEOUT=2.0
QAA_UI_RESPONSE_TIMEOUT=0.2
QAA_TEST_COVERAGE_THRESHOLD=90
EOF
        print_status "Created .env file"
    else
        print_status ".env file already exists"
    fi
    
    # Set environment-specific settings
    case $ENVIRONMENT in
        production)
            export QAA_DEBUG=false
            export QAA_LOG_LEVEL=WARNING
            print_status "Production settings applied"
            ;;
        staging)
            export QAA_DEBUG=true
            export QAA_LOG_LEVEL=INFO
            print_status "Staging settings applied"
            ;;
        development|*)
            export QAA_DEBUG=true
            export QAA_LOG_LEVEL=DEBUG
            print_status "Development settings applied"
            ;;
    esac
}

# Install dependencies
install_dependencies() {
    echo ""
    echo "Installing dependencies..."
    
    if [ -f "pyproject.toml" ]; then
        uv sync
        print_status "Dependencies installed via uv"
    else
        print_error "pyproject.toml not found"
        exit 1
    fi
}

# Run tests
run_tests() {
    echo ""
    echo "Running tests..."
    
    if [ "$ENVIRONMENT" == "production" ]; then
        print_warning "Skipping tests in production deployment"
        return 0
    fi
    
    uv run pytest tests/unit/ --override-ini="addopts=" -q
    if [ $? -eq 0 ]; then
        print_status "All tests passed"
    else
        print_error "Tests failed"
        exit 1
    fi
}

# Start application
start_application() {
    echo ""
    echo "Starting application..."
    
    case $1 in
        api)
            echo "Starting API server..."
            uv run uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
            ;;
        web)
            echo "Starting Web server..."
            uv run uvicorn src.web.main:app --host 0.0.0.0 --port 8000 --reload
            ;;
        cli)
            echo "Starting CLI..."
            uv run python -m src.cli.main "$@"
            ;;
        *)
            echo "Starting Web server (default)..."
            uv run uvicorn src.web.main:app --host 0.0.0.0 --port 8000 --reload
            ;;
    esac
}

# Main deployment flow
main() {
    check_prerequisites
    setup_environment
    install_dependencies
    
    if [ "$2" != "--skip-tests" ]; then
        run_tests
    fi
    
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}Deployment Complete!${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
    echo "To start the application, run one of:"
    echo "  ./scripts/deploy.sh $ENVIRONMENT api    # Start API server"
    echo "  ./scripts/deploy.sh $ENVIRONMENT web    # Start Web server"
    echo "  ./scripts/deploy.sh $ENVIRONMENT cli    # Start CLI"
    echo ""
    
    # If a service type was specified, start it
    if [ -n "$3" ]; then
        start_application "$3"
    fi
}

# Run main function
main "$@"
